Refactor build and preparation workflows: streamline input handling, remove variant options, and enhance bypass functionality in kernel build process

diff --git a/.github/actions/build-kernel/action.yml b/.github/actions/build-kernel/action.yml
--- a/.github/actions/build-kernel/action.yml
+++ b/.github/actions/build-kernel/action.yml
@@ -1,5 +1,12 @@
 name: 'Build Kernel'
 description: 'Builds kernel using legacy build.sh or Bazel (kleaf)'
+inputs:
+  bypass:
+    description: 'Whether to add the bypass hack or not'
+    required: true
+  version:
+    description: 'Kernel config version (e.g., android14-6.1)'
+    required: true
 
 runs:
   using: composite
@@ -9,6 +16,25 @@ runs:
     working-directory: ${{ github.workspace }}/kernel
     run: |
       set -euo pipefail
+      if [ "${{ inputs.bypass }}" = "true" ]; then
+        if [[ ${{ inputs.version }} == "android14-6.1" || ${{ inputs.version }} == "android15-6.6" || ${{ inputs.version }} == "android16-6.12" ]]; then
+          TARGET_FILE="${{ github.workspace }}/kernel/common/kernel/module/version.c"
+        else
+          TARGET_FILE="${{ github.workspace }}/kernel/common/kernel/module.c"
+        fi
+
+        sed -i '/bad_version:/{:a;n;/return 0;/{s/return 0;/return 1;/;b};ba}' "$TARGET_FILE"
+
+        if ! grep -A 5 "bad_version:" "$TARGET_FILE" | grep -q "return 1;"; then
+          echo "Patch failed! 'return 1;' not found at bad_version:"
+          grep -A 10 "bad_version:" "$TARGET_FILE" || true
+          exit 1
+        fi
+      else
+        echo "Bypass hack not applied as per input parameter."
+      fi
+  
+      rm -rf "out"
 
       GKI_KCONFIG_FRAGMENT_PATH="${{ github.workspace }}/wild_gki.fragment"
       GKI_DEFCONFIG_WRAPPER_PATH="${{ github.workspace }}/wild_gki.wrap.sh"
@@ -38,12 +64,12 @@ runs:
         GKI_BUILD_CONFIG_FRAGMENT="${GKI_BUILD_CONFIG_FRAGMENT_PATH}" \
         BUILD_CONFIG=common/build.config.gki.aarch64 \
         build/build.sh -j"$(nproc)" \
-        CC="$CC" \
-        CXX="$CXX" \
-        HOSTCC="$HOSTCC" \
-        HOSTCXX="$HOSTCXX" \
-        LD="$LD" \
-        HOSTLD="$HOSTLD"
+        CC="/usr/bin/ccache clang" \
+        CXX="/usr/bin/ccache clang+" \
+        HOSTCC="/usr/bin/ccache clang" \
+        HOSTCXX="/usr/bin/ccache clang+" \
+        LD="${{ github.workspace }}/kernel/common/ld-wrapper" \
+        HOSTLD="${{ github.workspace }}/kernel/common/ld-wrapper"
       else
         cp "${{ github.workspace }}/wild_gki.fragment" common/arch/arm64/configs/wild_gki.fragment
         tools/bazel build \
@@ -53,3 +79,6 @@ runs:
           --disk_cache="$BAZEL_CACHE_DIR" \
           //common:kernel_aarch64
       fi
+
+      ls
+      ls out
